<?php
  class Keke_witkey_free_task_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_task_id;  		 public $_uid; 		 public $_username; 		 public $_task_title; 		 public $_task_desc; 		 public $_task_file; 		 public $_task_pic; 		 public $_leave_num; 		 public $_focus_num; 		 public $_view_num; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_free_task_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_free_task";		 }	    
	    		public function getTask_id(){			 return $this->_task_id ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getTask_title(){			 return $this->_task_title ;		}		public function getTask_desc(){			 return $this->_task_desc ;		}		public function getTask_file(){			 return $this->_task_file ;		}		public function getTask_pic(){			 return $this->_task_pic ;		}		public function getLeave_num(){			 return $this->_leave_num ;		}		public function getFocus_num(){			 return $this->_focus_num ;		}		public function getView_num(){			 return $this->_view_num ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setTask_id($value){ 			 $this->_task_id = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setTask_title($value){ 			 $this->_task_title = $value;		}		public function setTask_desc($value){ 			 $this->_task_desc = $value;		}		public function setTask_file($value){ 			 $this->_task_file = $value;		}		public function setTask_pic($value){ 			 $this->_task_pic = $value;		}		public function setLeave_num($value){ 			 $this->_leave_num = $value;		}		public function setFocus_num($value){ 			 $this->_focus_num = $value;		}		public function setView_num($value){ 			 $this->_view_num = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_free_task  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_free_task(){		 		 $data =  array(); 					if(!is_null($this->_task_id)){ 				 $data['task_id']=$this->_task_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_task_title)){ 				 $data['task_title']=$this->_task_title;			}			if(!is_null($this->_task_desc)){ 				 $data['task_desc']=$this->_task_desc;			}			if(!is_null($this->_task_file)){ 				 $data['task_file']=$this->_task_file;			}			if(!is_null($this->_task_pic)){ 				 $data['task_pic']=$this->_task_pic;			}			if(!is_null($this->_leave_num)){ 				 $data['leave_num']=$this->_leave_num;			}			if(!is_null($this->_focus_num)){ 				 $data['focus_num']=$this->_focus_num;			}			if(!is_null($this->_view_num)){ 				 $data['view_num']=$this->_view_num;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_task_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_free_task		 * @return int affected_rows		 */		function edit_keke_witkey_free_task(){ 		 		 $data =  array();  					if(!is_null($this->_task_id)){ 				 $data['task_id']=$this->_task_id;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_task_title)){ 				 $data['task_title']=$this->_task_title;			}			if(!is_null($this->_task_desc)){ 				 $data['task_desc']=$this->_task_desc;			}			if(!is_null($this->_task_file)){ 				 $data['task_file']=$this->_task_file;			}			if(!is_null($this->_task_pic)){ 				 $data['task_pic']=$this->_task_pic;			}			if(!is_null($this->_leave_num)){ 				 $data['leave_num']=$this->_leave_num;			}			if(!is_null($this->_focus_num)){ 				 $data['focus_num']=$this->_focus_num;			}			if(!is_null($this->_view_num)){ 				 $data['view_num']=$this->_view_num;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('task_id' => $this->_task_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_free_task,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_free_task($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_free_task records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_free_task(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_free_task, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_free_task(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where task_id = $this->_task_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>