<?php
  class Keke_witkey_weibo_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_weibo_id;  		 public $_obj_id; 		 public $_obj_type; 		 public $_obj_cash_cove; 		 public $_obj_cash; 		 public $_obj_username; 		 public $_obj_uid; 		 public $_detail_type; 		 public $_obj_title; 		 public $_op_type; 		 public $_op_uid; 		 public $_op_username; 		 public $_leave_num; 		 public $_focus_num; 		 public $_work_num; 		 public $_on_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_weibo_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_weibo";		 }	    
	    		public function getWeibo_id(){			 return $this->_weibo_id ;		}		public function getObj_id(){			 return $this->_obj_id ;		}		public function getObj_type(){			 return $this->_obj_type ;		}		public function getObj_cash_cove(){			 return $this->_obj_cash_cove ;		}		public function getObj_cash(){			 return $this->_obj_cash ;		}		public function getObj_username(){			 return $this->_obj_username ;		}		public function getObj_uid(){			 return $this->_obj_uid ;		}		public function getDetail_type(){			 return $this->_detail_type ;		}		public function getObj_title(){			 return $this->_obj_title ;		}		public function getOp_type(){			 return $this->_op_type ;		}		public function getOp_uid(){			 return $this->_op_uid ;		}		public function getOp_username(){			 return $this->_op_username ;		}		public function getLeave_num(){			 return $this->_leave_num ;		}		public function getFocus_num(){			 return $this->_focus_num ;		}		public function getWork_num(){			 return $this->_work_num ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setWeibo_id($value){ 			 $this->_weibo_id = $value;		}		public function setObj_id($value){ 			 $this->_obj_id = $value;		}		public function setObj_type($value){ 			 $this->_obj_type = $value;		}		public function setObj_cash_cove($value){ 			 $this->_obj_cash_cove = $value;		}		public function setObj_cash($value){ 			 $this->_obj_cash = $value;		}		public function setObj_username($value){ 			 $this->_obj_username = $value;		}		public function setObj_uid($value){ 			 $this->_obj_uid = $value;		}		public function setDetail_type($value){ 			 $this->_detail_type = $value;		}		public function setObj_title($value){ 			 $this->_obj_title = $value;		}		public function setOp_type($value){ 			 $this->_op_type = $value;		}		public function setOp_uid($value){ 			 $this->_op_uid = $value;		}		public function setOp_username($value){ 			 $this->_op_username = $value;		}		public function setLeave_num($value){ 			 $this->_leave_num = $value;		}		public function setFocus_num($value){ 			 $this->_focus_num = $value;		}		public function setWork_num($value){ 			 $this->_work_num = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * insert into  keke_witkey_weibo  ,or add new record		 * @return int last_insert_id		 */		function create_keke_witkey_weibo(){		 		 $data =  array(); 					if(!is_null($this->_weibo_id)){ 				 $data['weibo_id']=$this->_weibo_id;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_obj_type)){ 				 $data['obj_type']=$this->_obj_type;			}			if(!is_null($this->_obj_cash_cove)){ 				 $data['obj_cash_cove']=$this->_obj_cash_cove;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_obj_username)){ 				 $data['obj_username']=$this->_obj_username;			}			if(!is_null($this->_obj_uid)){ 				 $data['obj_uid']=$this->_obj_uid;			}			if(!is_null($this->_detail_type)){ 				 $data['detail_type']=$this->_detail_type;			}			if(!is_null($this->_obj_title)){ 				 $data['obj_title']=$this->_obj_title;			}			if(!is_null($this->_op_type)){ 				 $data['op_type']=$this->_op_type;			}			if(!is_null($this->_op_uid)){ 				 $data['op_uid']=$this->_op_uid;			}			if(!is_null($this->_op_username)){ 				 $data['op_username']=$this->_op_username;			}			if(!is_null($this->_leave_num)){ 				 $data['leave_num']=$this->_leave_num;			}			if(!is_null($this->_focus_num)){ 				 $data['focus_num']=$this->_focus_num;			}			if(!is_null($this->_work_num)){ 				 $data['work_num']=$this->_work_num;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_weibo_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * edit table keke_witkey_weibo		 * @return int affected_rows		 */		function edit_keke_witkey_weibo(){ 		 		 $data =  array();  					if(!is_null($this->_weibo_id)){ 				 $data['weibo_id']=$this->_weibo_id;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_obj_type)){ 				 $data['obj_type']=$this->_obj_type;			}			if(!is_null($this->_obj_cash_cove)){ 				 $data['obj_cash_cove']=$this->_obj_cash_cove;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_obj_username)){ 				 $data['obj_username']=$this->_obj_username;			}			if(!is_null($this->_obj_uid)){ 				 $data['obj_uid']=$this->_obj_uid;			}			if(!is_null($this->_detail_type)){ 				 $data['detail_type']=$this->_detail_type;			}			if(!is_null($this->_obj_title)){ 				 $data['obj_title']=$this->_obj_title;			}			if(!is_null($this->_op_type)){ 				 $data['op_type']=$this->_op_type;			}			if(!is_null($this->_op_uid)){ 				 $data['op_uid']=$this->_op_uid;			}			if(!is_null($this->_op_username)){ 				 $data['op_username']=$this->_op_username;			}			if(!is_null($this->_leave_num)){ 				 $data['leave_num']=$this->_leave_num;			}			if(!is_null($this->_focus_num)){ 				 $data['focus_num']=$this->_focus_num;			}			if(!is_null($this->_work_num)){ 				 $data['work_num']=$this->_work_num;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('weibo_id' => $this->_weibo_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * query table: keke_witkey_weibo,if isset where return where record,else return all record		 * @return array 		 */		function query_keke_witkey_weibo($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    /**		 * query count keke_witkey_weibo records,if iset where query by where 		 * @return int count records		 */		function count_keke_witkey_weibo(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    /**		 * delete table keke_witkey_weibo, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del_keke_witkey_weibo(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where weibo_id = $this->_weibo_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>