<?php	defined ( 'IN_KEKE' ) or exit ( 'Access Denied' );
$page_title='商品推广'.'- '.$_K['html_title'];
$model_list = $kekezu->_model_list;
$page_obj = $kekezu->_page_obj;
$page_obj->setAjax ( '1' );
$page_obj->setAjaxDom ( 'ajax_list' );
$page or $page = 1;
$page_size or $page_size = 10;
$url = "index.php?do=prom&view=good&prom_code=service";
$effect_mode_service = keke_prom_class::get_prom_rule('service');
$prom_rule = keke_prom_class::get_prom_rule ( 'service' );
$goods_config = unserialize($model_list[6][config]);
$table_title = array ($_lang['belong_model'], $_lang['goods_title'], $_lang['goods_cash'], $_lang['pro_cash'] );
$ser_obj = new Keke_witkey_service_class ();
$where = " service_status='2' ";
$prom_rule ['model'] and $where .= " and model_id in (" . $prom_rule [model] . ") ";
$prom_rule ['indus_string'] and $where .= " and indus_id in (" . $prom_rule [indus_string] . ") ";
$where.=" order by on_time desc ";
$ser_obj->setWhere ( $where );
$count = intval ( $ser_obj->count_keke_witkey_service () );
$pages = $page_obj->getPages ( $count, $page_size, $page, $url );
$ser_obj->setWhere ( $where . $pages ['where'] );
$prom_list = $ser_obj->query_keke_witkey_service ();
require keke_tpl_class::template ( "tpl/" . $_K ['template'] . "/" . $do . "/" .$do."_". $view );